name: automerge

on:
  push:
    branches:
      - 'staging'
  pull_request:
    branches:
      - 'staging'
    types:
      - labeled
      - unlabeled
      - synchronize
      - ready_for_review
  status:
jobs:
  automerge:
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging' || contains(github.event.pull_request.labels.*.name, 'QA approved-gha') || github.event.context == 'continuous-integration/heroku' && github.event.state == 'success'
    runs-on: ubuntu-20.04
    steps:
      - id: automerge
        name: automerge
        uses: "emeritus-tech/em-automerge-action@fix-base-branch-update"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "QA approved-gha,deploy-gha,!on hold,!env-variables,!migrations"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "Auto-merge {pullRequest.title} (#{pullRequest.number})"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "2"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "2"
          BASE_BRANCHES: "staging"
          UPDATE_LABELS: "QA approved-gha,queue-gha"
          UPDATE_METHOD: "merge"
